sudo: required
services:
  - docker

before_install:
  - docker build -t alepoletto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alepoletto/react-test npm test -- --coverage

after_success:
  - docker build -t alepoletto/multi-client -f  ./client
  - docker build -t alepoletto/multi-nginx -f  ./nginx
  - docker build -t alepoletto/multi-server -f  ./server
  - docker build -t alepoletto/multi-worker -f  ./worker
  #log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push alepoletto/multi-client
  - docker push alepoletto/multi-nginx
  - docker push alepoletto/multi-server
  - docker push alepoletto/multi-worker
