sudo: required
services:
  - docker

before_install:
  - docker build -t alepoletto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alepoletto/react-test npm test -- --coverage

after_success:
  - docker build -t alepoletto/multi-client ./client
  - docker build -t alepoletto/multi-nginx ./nginx
  - docker build -t alepoletto/multi-server ./server
  - docker build -t alepoletto/multi-worker ./worker
  #log to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push alepoletto/multi-client
  - docker push alepoletto/multi-nginx
  - docker push alepoletto/multi-server
  - docker push alepoletto/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-923376952282
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
